### ISSUE TITLE
perguntas: repositorio do Readme.md sumiu do meu perfil

### ISSUE THREAD

**Issue by toptoptuns** [marehead/marehead#7]
### Discussed in https://github.com/mlopezlr/mlopezlr/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **mlopezlr** July 18, 2022</sup>
como recuperar readme.md do deashboard que sumiu troquei somente o readme.md para profile.md como faço para recuperar o ultimo save?</div>

**Comment by mlopezlr** [comment]
basta ir em seu repositorio readme.md que vc renomeou para profile.md e nomear de volta para README.md.

**Comment by mlopezlr** [comment]
respondido sua pergunta?

**Comment by toptoptuns** [comment]
S, vlw!
